spring:
  profiles:
    default: production

---
spring:
  profiles: development
  
app:
  musicDir: E:/music
  indexDir: E:/music_index
  
---
spring:
  profiles: production
  resources:
    cachePeriod: 31556926  
      
app:
  musicDir: /opt/music
  indexDir: /opt/music_index
  nginxSendFileContext: /musiclib
